# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025-2026  Philipp Emanuel Weidmann <pew@worldwidemann.com> + contributors

"""
Self-calibrated KL divergence.

The stock KL divergence scorer compares the original and the modified model
at a single position: the first response token, on a fixed prompt set. On
heavily post-trained models that position is nearly deterministic (a thinking
tag, "Sure", the start of a tool call), so the measurement is both
hypersensitive to tiny shifts and blind to anything that happens later in the
response.

This scorer borrows the "self-calibration" idea from the ExLlamaV3 quantizer:
the reference corpus is generated by the *original model itself* from the
configured prompts, once, before optimization. Every trial then runs a
teacher-forced forward pass over those same prompt + response sequences and
measures the KL divergence from the original model's distribution at every
response position. Because the token prefix is identical for both models at
every position, the per-position divergences are directly comparable and do
not compound (the problem with comparing two free-running generations).

The score is the mean over prompts of the mean per-token KL divergence. The
per-position distribution (95th percentile and maximum) is shown alongside it,
because a low mean can hide a few badly damaged positions.

Memory: storing the original model's full distribution at every position
(prompts x tokens x vocabulary) is prohibitive, so by default only its `top_k`
most likely tokens are kept, plus the total mass of everything else as one
"tail" bucket. The KL divergence is then computed between the two models'
distributions coarsened onto that partition. By the data processing
inequality this is a lower bound on the exact KL divergence, and it is tight
when the tail mass is small, which is the typical case. Mass the modified
model moves *outside* the original model's top-k (e.g. onto garbage tokens) is
captured by the tail bucket. Set `top_k = 0` to keep full distributions and
compute the exact value.
"""

import hashlib
import json
import math
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch
import torch.nn.functional as F
from optuna import TrialPruned
from pydantic import BaseModel, Field, NonNegativeInt
from torch import Tensor

from heretic.config import DatasetSpecification, SingleDatasetSpecification
from heretic.plugin import Context
from heretic.scorer import Score, Scorer
from heretic.system import empty_cache
from heretic.utils import Prompt, format_dataset_specification, print

# Soft budget for the transient full-vocabulary logits of one teacher-forced
# batch, used to pick the batch size automatically.
LOGITS_MEMORY_BUDGET = 2 * 1024**3

# Floor for the log-probability the modified model assigns to the tail bucket.
# Without it, a modified model that (within float32) puts no mass at all outside
# the original model's top-k would make the tail term infinite whenever the
# original model had any tail mass.
TAIL_LOGPROB_FLOOR = math.log(1e-10)


class Settings(BaseModel):
    prompts: DatasetSpecification = Field(
        default=SingleDatasetSpecification(
            dataset="mlabonne/harmless_alpaca",
            split="test[:100]",
            column="text",
        ),
        description=(
            "Dataset of prompts the original model answers to build the reference corpus. "
            "Should resemble the model's real workload (chat, coding, tool use, system prompts)."
        ),
    )

    max_response_tokens: NonNegativeInt = Field(
        default=0,
        description=(
            "Maximum length of each reference response, in tokens "
            "(0 = use the global max_response_length)."
        ),
    )

    top_k: NonNegativeInt = Field(
        default=1024,
        description=(
            "Number of most likely tokens of the original model's distribution kept at each "
            "position; the remaining mass is tracked as a single tail bucket. 0 keeps the full "
            "distribution (exact KL divergence, but memory grows with the vocabulary size)."
        ),
    )

    batch_size: NonNegativeInt = Field(
        default=0,
        description=(
            "Number of sequences per teacher-forced forward pass "
            "(0 = derive from the vocabulary size and response length to bound memory use)."
        ),
    )

    cache_dir: str | None = Field(
        default=None,
        description=(
            "Directory where the generated reference responses are cached, keyed on the "
            "model, the prompts and the generation settings, so that later runs on the same "
            "original model skip generation (None = <study_checkpoint_dir>/self_calibrated_kl, "
            "empty string = do not cache)."
        ),
    )

    answer_start_markers: list[str] = Field(
        default=["</think>", "<|end_of_thought|>"],
        description=(
            "Strings marking the end of a reasoning span in a reference response. Positions up to "
            "and including the first marker are reported as 'thinking', the rest as 'answer', so "
            "that damage concentrated in the final answer is not averaged away by a long reasoning span."
        ),
    )


@dataclass
class Reference:
    prompt: Prompt
    response_token_ids: list[int]
    # Original model's log-probabilities at each response position, of shape
    # (response_length, top_k) when coarsened or (response_length, vocabulary) when exact.
    logprobs: Tensor
    # Token IDs the coarsened log-probabilities refer to, or None when exact.
    token_ids: Tensor | None
    # Log of the original model's mass outside the top-k, or None when exact.
    tail_logprob: Tensor | None
    # Index of the first response position that belongs to the final answer
    # (0 when the response has no reasoning span).
    answer_start: int


def log1mexp(x: Tensor) -> Tensor:
    """Numerically stable `log(1 - exp(x))` for `x <= 0`."""
    x = torch.clamp(x, max=0.0)
    return torch.where(
        x > -math.log(2),
        torch.log(-torch.expm1(x)),
        torch.log1p(-torch.exp(x)),
    )


def summarize_distribution(
    logits: Tensor, top_k: int
) -> tuple[Tensor, Tensor | None, Tensor | None]:
    """
    Turn `(positions, vocabulary)` logits into the stored reference form:
    `(logprobs, token_ids, tail_logprob)`, coarsened to `top_k` tokens when
    `0 < top_k < vocabulary`, exact otherwise.
    """
    logprobs = F.log_softmax(logits.float(), dim=-1)
    if top_k <= 0 or top_k >= logprobs.shape[-1]:
        return logprobs, None, None

    top_logprobs, top_token_ids = logprobs.topk(top_k, dim=-1)
    tail_logprob = log1mexp(torch.logsumexp(top_logprobs, dim=-1))
    return top_logprobs, top_token_ids, tail_logprob


def position_kl_divergence(
    logprobs: Tensor,
    token_ids: Tensor | None,
    tail_logprob: Tensor | None,
    logits: Tensor,
) -> Tensor:
    """
    KL(original || modified) at each position, given the stored reference
    form of the original model's distribution and the modified model's raw
    `(positions, vocabulary)` logits.
    """
    modified_logprobs = F.log_softmax(logits.float(), dim=-1)
    probabilities = logprobs.exp()

    if token_ids is None:
        return (probabilities * (logprobs - modified_logprobs)).sum(dim=-1)

    modified_top = modified_logprobs.gather(-1, token_ids)
    kl = (probabilities * (logprobs - modified_top)).sum(dim=-1)

    assert tail_logprob is not None
    tail_probability = tail_logprob.exp()
    modified_tail = torch.clamp(
        log1mexp(torch.logsumexp(modified_top, dim=-1)), min=TAIL_LOGPROB_FLOOR
    )
    tail_term = torch.where(
        tail_probability > 0,
        tail_probability * (tail_logprob - modified_tail),
        torch.zeros_like(tail_probability),
    )
    return kl + tail_term


def response_cache_key(
    model: str,
    model_commit: str | None,
    prompts: list[Prompt],
    max_tokens: int,
    response_prefix: str | None,
    chat_template_kwargs: dict[str, Any],
) -> str:
    """
    Content hash identifying a reference corpus: the original model, the exact
    prompts (system and user text), and everything that shapes greedy generation.
    """
    payload = {
        "model": model,
        "model_commit": model_commit,
        "prompts": [[prompt.system, prompt.user] for prompt in prompts],
        "max_tokens": max_tokens,
        "response_prefix": response_prefix,
        "chat_template_kwargs": chat_template_kwargs,
    }
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def load_response_cache(path: Path, key: str) -> list[list[int]] | None:
    """Return the cached response token IDs if `path` holds a corpus for `key`."""
    if not path.is_file():
        return None
    try:
        with open(path, encoding="utf-8") as file:
            data = json.load(file)
        if data.get("key") != key:
            return None
        return [list(map(int, token_ids)) for token_ids in data["responses"]]
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"[yellow]Ignoring unreadable response cache {path}: {error}[/]")
        return None


def save_response_cache(
    path: Path,
    key: str,
    model: str,
    prompts: list[Prompt],
    responses: list[list[int]],
    max_tokens: int,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "key": key,
        "model": model,
        "max_tokens": max_tokens,
        "prompts": [{"system": p.system, "user": p.user} for p in prompts],
        "responses": responses,
    }
    with open(path, "w", encoding="utf-8") as file:
        json.dump(data, file, ensure_ascii=False)


def find_answer_start(
    response_token_ids: list[int],
    decode: Callable[[list[int]], str],
    markers: list[str],
) -> int:
    """
    Index of the first response position after the first end-of-reasoning
    marker, found by decoding growing prefixes of the response. Returns 0
    when no marker occurs, i.e. the whole response counts as the answer.
    """
    if not markers or not any(
        marker in decode(response_token_ids) for marker in markers
    ):
        return 0
    for length in range(1, len(response_token_ids) + 1):
        text = decode(response_token_ids[:length])
        if any(marker in text for marker in markers):
            return min(length, len(response_token_ids))
    return 0


class SelfCalibratedKL(Scorer):
    """
    Per-token KL divergence from the original model, teacher-forced over
    responses the original model itself generated for in-domain prompts.
    Lower is better (less damage).
    """

    settings: Settings

    @property
    def reproducible(self) -> bool:
        return True

    @property
    def score_name(self) -> str:
        return "Self-calibrated KL"

    def init(self, ctx: Context) -> None:
        print()
        print(
            f"Loading self-calibrated KL prompts from [bold]{format_dataset_specification(self.settings.prompts)}[/]..."
        )
        prompts = ctx.load_prompts(self.settings.prompts)
        print(f"* [bold]{len(prompts)}[/] prompts loaded")

        max_tokens = (
            self.settings.max_response_tokens
            or self.heretic_settings.max_response_length
        )
        responses = self._load_or_generate_responses(ctx, prompts, max_tokens)
        sequences = [
            (prompt, token_ids)
            for prompt, token_ids in zip(prompts, responses)
            if token_ids
        ]

        dropped = len(prompts) - len(sequences)
        if dropped:
            print(
                f"  * [yellow]{dropped} prompts produced empty responses and were dropped[/]"
            )
        if not sequences:
            raise ValueError("The original model produced no reference responses")

        # Group sequences of similar length together to minimize padding
        # (and, on backends without an attention mask, its influence).
        sequences.sort(key=lambda item: len(item[0].user) + 4 * len(item[1]))

        total_tokens = sum(len(token_ids) for _, token_ids in sequences)
        self._max_response_length = max(len(token_ids) for _, token_ids in sequences)
        print(
            f"* [bold]{len(sequences)}[/] reference sequences, [bold]{total_tokens}[/] response tokens "
            f"(mean [bold]{total_tokens / len(sequences):.1f}[/], max [bold]{self._max_response_length}[/])"
        )

        tokenizer = ctx.get_model().tokenizer

        def decode(token_ids: list[int]) -> str:
            return tokenizer.batch_decode([token_ids], skip_special_tokens=False)[0]

        answer_starts = [
            find_answer_start(token_ids, decode, self.settings.answer_start_markers)
            for _, token_ids in sequences
        ]
        with_reasoning = sum(1 for start in answer_starts if start > 0)
        if with_reasoning:
            thinking_tokens = sum(answer_starts)
            print(
                f"* [bold]{with_reasoning}[/] responses contain a reasoning span "
                f"([bold]{thinking_tokens}[/] thinking tokens, "
                f"[bold]{total_tokens - thinking_tokens}[/] answer tokens)"
            )

        print("* Obtaining baseline per-token probability distributions...")
        self._batch_size = self.settings.batch_size or None
        self._references: list[Reference] = []
        covered_mass: list[Tensor] = []
        sequence_index = 0
        for batch, logits in self._forward_batches(ctx, sequences):
            for (prompt, token_ids), row_logits in zip(batch, logits):
                logprobs, top_token_ids, tail_logprob = summarize_distribution(
                    row_logits, self.settings.top_k
                )
                self._references.append(
                    Reference(
                        prompt=prompt,
                        response_token_ids=token_ids,
                        logprobs=logprobs.cpu(),
                        token_ids=None
                        if top_token_ids is None
                        else top_token_ids.cpu(),
                        tail_logprob=None
                        if tail_logprob is None
                        else tail_logprob.cpu(),
                        answer_start=answer_starts[sequence_index],
                    )
                )
                sequence_index += 1
                if tail_logprob is not None:
                    covered_mass.append((-tail_logprob.expm1()).cpu())
            del logits
            empty_cache()

        if covered_mass:
            coverage = torch.cat(covered_mass)
            print(
                f"* Top-[bold]{self.settings.top_k}[/] tokens cover [bold]{100 * coverage.mean():.3f}%[/] "
                f"of the original model's probability mass per position "
                f"(minimum [bold]{100 * coverage.min():.2f}%[/])"
            )

    def _cache_path(self, key: str) -> Path | None:
        cache_dir = self.settings.cache_dir
        if cache_dir is None:
            cache_dir = str(
                Path(self.heretic_settings.study_checkpoint_dir) / "self_calibrated_kl"
            )
        if not cache_dir:
            return None
        return Path(cache_dir) / f"{key[:16]}.json"

    def _load_or_generate_responses(
        self, ctx: Context, prompts: list[Prompt], max_tokens: int
    ) -> list[list[int]]:
        key = response_cache_key(
            self.heretic_settings.model,
            self.heretic_settings.model_commit,
            prompts,
            max_tokens,
            self.heretic_settings.response_prefix,
            self.heretic_settings.chat_template_kwargs,
        )
        path = self._cache_path(key)

        if path is not None:
            cached = load_response_cache(path, key)
            if cached is not None and len(cached) == len(prompts):
                print(f"* Loaded cached reference responses from [bold]{path}[/]")
                return cached

        print(
            f"* Generating reference responses with the original model (up to [bold]{max_tokens}[/] tokens each)..."
        )
        responses: list[list[int]] = []
        generation_batch_size = max(1, self.heretic_settings.batch_size)
        for start in range(0, len(prompts), generation_batch_size):
            batch = prompts[start : start + generation_batch_size]
            responses.extend(ctx.get_response_token_ids(batch, max_tokens))

        if path is not None:
            try:
                save_response_cache(
                    path,
                    key,
                    self.heretic_settings.model,
                    prompts,
                    responses,
                    max_tokens,
                )
                print(f"* Cached reference responses to [bold]{path}[/]")
            except OSError as error:
                print(f"  * [yellow]Could not write response cache {path}: {error}[/]")

        return responses

    def _forward_batches(
        self,
        ctx: Context,
        sequences: list[tuple[Prompt, list[int]]],
    ) -> Iterator[tuple[list[tuple[Prompt, list[int]]], list[Tensor]]]:
        """
        Yield `(batch, logits)` pairs for the given `(prompt, response_token_ids)`
        sequences, choosing the batch size from the first batch when unset.
        """
        if self._batch_size is None:
            # Probe with a single sequence to size the batches, then discard the
            # result so that the baseline and every trial see *identical*
            # batches. Backends without an attention mask (EXL3) let padding
            # influence the logits, so a different first batch would otherwise
            # register as divergence even between identical weights.
            probe_prompt, probe_token_ids = sequences[0]
            probe_logits = ctx.get_response_logits([probe_prompt], [probe_token_ids])
            self._batch_size = self._choose_batch_size(probe_logits[0])
            del probe_logits
            empty_cache()

        index = 0
        while index < len(sequences):
            batch = sequences[index : index + self._batch_size]
            logits = ctx.get_response_logits(
                [prompt for prompt, _ in batch],
                [token_ids for _, token_ids in batch],
            )
            yield batch, logits
            index += len(batch)

    def _choose_batch_size(self, sample_logits: Tensor) -> int:
        vocabulary_size = sample_logits.shape[-1]
        bytes_per_sequence = (
            (self._max_response_length + 1)
            * vocabulary_size
            * sample_logits.element_size()
        )
        batch_size = max(1, LOGITS_MEMORY_BUDGET // bytes_per_sequence)
        if self.heretic_settings.batch_size > 0:
            batch_size = min(batch_size, self.heretic_settings.batch_size)
        return int(batch_size)

    def get_score(self, ctx: Context) -> Score:
        sequences = [
            (reference.prompt, reference.response_token_ids)
            for reference in self._references
        ]
        per_prompt: list[Tensor] = []
        per_position: list[Tensor] = []
        thinking_positions: list[Tensor] = []
        answer_positions: list[Tensor] = []
        reference_index = 0
        for batch, logits in self._forward_batches(ctx, sequences):
            for row_logits in logits:
                reference = self._references[reference_index]
                reference_index += 1
                device = row_logits.device
                kl = position_kl_divergence(
                    reference.logprobs.to(device),
                    None
                    if reference.token_ids is None
                    else reference.token_ids.to(device),
                    None
                    if reference.tail_logprob is None
                    else reference.tail_logprob.to(device),
                    row_logits,
                ).cpu()
                per_position.append(kl)
                per_prompt.append(kl.mean())
                thinking_positions.append(kl[: reference.answer_start])
                answer_positions.append(kl[reference.answer_start :])
            del logits
            empty_cache()

        positions = torch.cat(per_position)
        mean = torch.stack(per_prompt).mean().item()

        if not math.isfinite(mean):
            # Same reasoning as the KLDivergence scorer: the modified model's
            # forward pass produced non-finite logits, so every score is
            # meaningless. Prune the trial instead of poisoning the Pareto front.
            print(
                "  * [yellow]Self-calibrated KL is non-finite (modification blew up); "
                "pruning trial.[/]"
            )
            raise TrialPruned("Non-finite self-calibrated KL divergence")

        p95 = torch.quantile(positions, 0.95).item()
        maximum = positions.max().item()
        details = f"per token: p95 {p95:.3f}, max {maximum:.3f}"

        thinking = torch.cat(thinking_positions)
        answer = torch.cat(answer_positions)
        if thinking.numel() > 0 and answer.numel() > 0:
            details += f"; thinking {thinking.mean().item():.4f}, answer {answer.mean().item():.4f}"

        return Score(
            value=mean,
            rich_display=f"[bold]{mean:.4f}[/] [grey50]({details})[/]",
            md_display=f"{mean:.4f}",
        )

    def get_baseline_score(self, ctx: Context) -> Score:
        return Score(
            value=0,
            rich_display="[bold]0[/] [italic](by definition)[/]",
            md_display="0 *(by definition)*",
        )
